### ISSUE TITLE
Disable downloadJar logs if trace or verbose are setted to false

### ISSUE THREAD

**Issue by amadridlar** [mock-server/mockserver-node#19]
**Describe the feature request**
Only print logs of ```downloadJar``` module if verbose or trace options are enabled

**What you are trying to do**
When the server is statring, the following logs are printed:
```shell
Skipping {
  "host": "oss.sonatype.org",
  "path": "/content/repositories/releases/org/mock-server/mockserver-netty/5.7.0/mockserver-netty-5.7.0-jar-with-dependencies.jar",
  "port": 443
} as file already downloaded
```
I would like that if I do not want any logs, this message will not be printed

**The solution you'd like**
In ```downloadJar.js``` file, put all console.log into an if conditional where checks if trace or verbose are enabled

**Comment by amadridlar** [comment]
I made a pull request #20 with a proposal for this enhancement

**Comment by amadridlar** [comment]
Hi @jamesdbloom. Are you interested in this enhancement?

**Comment by jamesdbloom** [comment]
@amadridlar sorry I haven't manually checked issue in this repo and the notifications setting was wrong so I didn't notice.  I have now merged your PR thanks for your work.  I'm expecting to do another minor release next week.
